mypojisteni/mypojisteni/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pojisteni/', include('pojisteni.urls')),
    path('admin/', admin.site.urls),
]

mypojisteni/pojisteni/urls.py
from django.urls import path

from pojisteni import views


urlpatterns = [
    path('', views.seznam_pojistenych, name='seznam_pojistenych'),
    path('pojisteny/<int:pk>/', views.detail_pojisteneho, name='detail_pojisteneho'),
    path('pojisteni/novy/', views.novy_pojisteny, name='novy_pojisteny'),
    path('pojisteny/<int:pk>/pridat/', views.pridat_pojisteni, name='pridat_pojisteni'),
    path('pojisteny/<int:pk>/editovat/', views.editovat_pojisteneho, name='editovat_pojisteneho'),
    path('pojisteny/<int:pk>/odstranit/', views.odstranit_pojisteneho, name='odstranit_pojisteneho'),
    path('pojisteni/<int:pk>/editovat/', views.editovat_pojisteni, name='editovat_pojisteni'),
    path('pojisteni/<int:pk>/odstranit/', views.odstranit_pojisteni, name='odstranit_pojisteni'),

]

mypojisteni/pojisteni/models.py
from django.db import models

# Create your models here.

class Pojisteny(models.Model):
    jmeno = models.CharField(max_length=100)
    prijmeni = models.CharField(max_length=100)
    email = models.EmailField()
    cislo_popisne = models.CharField(max_length=10)
    telefon = models.CharField(max_length=20)
    ulice = models.CharField(max_length=100)
    psc = models.CharField(max_length=10)
    mesto = models.CharField(max_length=100)
    
    def __str__(self):
        return self.jmeno + ' ' + self.prijmeni



class Pojisteni(models.Model):
    pojisteny_objekt = models.ForeignKey(Pojisteny, on_delete=models.CASCADE, related_name='pojisteni_set')
    nazev = models.CharField(max_length=100, blank=True)
    castka = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    predmet = models.CharField(max_length=100, blank=True)
    platnost_od = models.DateField(blank=True, null=True)
    platnost_do = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'pojisteni'

    def __str__(self):
        return f'Pojisteni číslo {self.id} - {self.predmet}'

mypojisteni/pojisteni/forms.py
from django import forms
from .models import Pojisteny, Pojisteni


class PojistenyForm(forms.ModelForm):
    class Meta:
        model = Pojisteny
        fields = ['jmeno', 'prijmeni', 'email', 'telefon', 'ulice', 'cislo_popisne', 'mesto', 'psc']


class PojisteniForm(forms.ModelForm):
    class Meta:
        model = Pojisteni
        fields = ['nazev', 'castka', 'predmet', 'platnost_od', 'platnost_do']
        widgets = {
            'platnost_od': forms.DateInput(attrs={'type': 'date'}),
            'platnost_do': forms.DateInput(attrs={'type': 'date'}),
        }
        initial = {'castka': '...' }  # Předvyplněná hodnota částky

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nazev'].widget.attrs['class'] = 'form-control'
        self.fields['castka'].widget.attrs['class'] = 'form-control'
        self.fields['predmet'].widget.attrs['class'] = 'form-control'

mypojisteni/pojisteni/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q
# Create your views here.
from django.http import HttpResponse
from django.urls import reverse
from pojisteni.models import Pojisteny, Pojisteni
from pojisteni.forms import PojisteniForm, PojistenyForm

from pojisteni.forms import PojistenyForm
from pojisteni.forms import PojisteniForm


from .models import Pojisteny


# def seznam_pojistenych(request):
#     pojisteni = Pojisteny.objects.all()
#     return render(request, 'seznam_pojistenych.html', {'pojisteni': pojisteni})


def seznam_pojistenych(request):
    query = request.GET.get('q')
    pojisteni = Pojisteny.objects.all()
    
    if query:
        query_parts = query.split(" ")
        for part in query_parts:
            pojisteni = pojisteni.filter(Q(jmeno__icontains=part) | Q(prijmeni__icontains=part) |
                                         Q(jmeno__iregex=fr".*\b{part}\b.*") | Q(prijmeni__iregex=fr".*\b{part}\b.*"))
    
    return render(request, 'seznam_pojistenych.html', {'pojisteni': pojisteni})


def detail_pojisteneho(request, pk):
    pojisteny = get_object_or_404(Pojisteny, pk=pk)
    return render(request, 'detail_pojisteneho.html', {'pojisteny': pojisteny})


def novy_pojisteny(request):
    if request.method == 'POST':
        # Zpracování formuláře pro přidání nového pojištěnce
        form = PojistenyForm(request.POST)
        if form.is_valid():
            form.save()
            # Přesměrování na seznam pojištěných po uložení
            return redirect('seznam_pojistenych')
    else:
        # Zobrazení prázdného formuláře pro přidání nového pojištěnce
        form = PojistenyForm()

    return render(request, 'novy_pojisteny.html', {'form': form})


def pridat_pojisteni(request, pk):
    pojisteny = get_object_or_404(Pojisteny, pk=pk)
    
    if request.method == 'POST':
        form = PojisteniForm(request.POST)
        if form.is_valid():
            pojisteni = form.save(commit=False)
            pojisteni.pojisteny_objekt_id = pojisteny.pk
            pojisteni.save()
            return redirect('detail_pojisteneho', pk=pojisteny.pk)
    else:
        form = PojisteniForm()
    
    return render(request, 'pridat_pojisteni.html', {'form': form, 'pojisteny': pojisteny})





def editovat_pojisteneho(request, pk):
    pojisteny = get_object_or_404(Pojisteny, pk=pk)

    if request.method == 'POST':
        form = PojistenyForm(request.POST, instance=pojisteny)
        if form.is_valid():
            form.save()
            return redirect('detail_pojisteneho', pk=pojisteny.pk)
    else:
        form = PojistenyForm(instance=pojisteny)

    return render(request, 'editovat_pojisteneho.html', {'form': form, 'pojisteny': pojisteny})

def odstranit_pojisteneho(request, pk):
    pojisteny = get_object_or_404(Pojisteny, pk=pk)

    if request.method == 'POST':
        pojisteny.delete()
        return redirect('seznam_pojistenych')

    return render(request, 'odstranit_pojisteneho.html', {'pojisteny': pojisteny})



def editovat_pojisteni(request, pk):
    pojisteni = get_object_or_404(Pojisteni, pk=pk)

    if request.method == 'POST':
        form = PojisteniForm(request.POST, instance=pojisteni)
        if form.is_valid():
            form.save()
            return redirect('detail_pojisteneho', pk=pojisteni.pojisteny_objekt.pk)
    else:
        form = PojisteniForm(instance=pojisteni)
        # Předvyplnění hodnoty částky v poli formuláře
        form.fields['castka'].initial = pojisteni.castka

    # return render(request, 'editovat_pojisteni.html', {'form': form})
    return render(request, 'editovat_pojisteni.html', {'pojisteni': pojisteni})




def odstranit_pojisteni(request, pk):
    pojisteni = get_object_or_404(Pojisteni, pk=pk)
    pojisteny = pojisteni.pojisteny_objekt
    
    if request.method == 'POST':
        # Potvrzení odstranění pojistění
        pojisteni.delete()
        return redirect('seznam_pojistenych')
    
    # Zobrazit potvrzovací stránku pro odstranění pojistění
    return render(request, 'odstranit_pojisteni.html', {'pojisteni': pojisteni, 'pojisteny': pojisteny})

mypojisteni/pojisteni/templates/detail_pojisteneho.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">

{% block content %}
<!-- detail_pojisteneho.html -->
<div class="row">
    <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">    
<h1>Detail pojištěného</h1>

<div>
    <h2>Informace o pojištěném</h2>
    <p class="informace">
        <strong>Jméno:</strong> {{ pojisteny.jmeno }}<br>
        <strong>Příjmení:</strong> {{ pojisteny.prijmeni }}<br>
        <strong>Adresa:</strong> {{ pojisteny.ulice }} {{ pojisteny.cislo_popisne }}, {{ pojisteny.mesto }}<br>
        <strong>Email:</strong> {{ pojisteny.email }}<br>
        <strong>Telefon:</strong> {{ pojisteny.telefon }}<br>
    </p>
    <div class="btn-informace">
        <a href="{% url 'editovat_pojisteneho' pojisteny.pk %}" class="btn btn-primary btn-edit">Editovat pojištěného</a>
        <a href="{% url 'odstranit_pojisteneho' pojisteny.pk %}" class="btn btn-odstr">Odstranit pojištěného</a>
        <a href="{% url 'pridat_pojisteni' pojisteny.pk %}" class="btn btn-primary btn-pridat">Přidat pojištění</a>
        <a href="{% url 'seznam_pojistenych' %}" class="btn btn-primary btn-zpet">Zpět</a>
    </div>
</div>

<div>
    <h2>Sjednaná pojištění</h2>
    <table class="pojisteni-table">
        <thead>
            <tr>
                <th>Pojištění</th>
                <th>Částka</th>
                <th>Možnosti</th>
            </tr>
        </thead>
        <tbody>
            {% for pojisteni in pojisteny.pojisteni_set.all %}
            <tr>
                <td>{{ pojisteni.nazev }}</td>
                <td>{{ pojisteni.castka }}</td>
                <td>
                    <a href="{% url 'editovat_pojisteni' pojisteni.pk %}" class="btn btn-primary btn-edit">Editovat pojištění</a>
                    <a href="{% url 'odstranit_pojisteni' pojisteni.pk %}" class="btn btn-primary btn-odstr">Odstranit pojištění</a>
                </td>
                    
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <footer class="pata">
        <div class="row">
            <div class="social">
                <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
                </p>
                <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
                </p>
            </div>
            
      
            <div class="copytext">
                Copywrite &copy; 2023 emixx company.
            </div>
        </div>
      </footer>
</div>


{% endblock %}

mypojisteni/pojisteni/templates/editovat_pojisteneho.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">

{% block content %}
<div class="row">
  <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">
  <h1>Editace pojistěného</h1>

  <form method="POST" action="">
    {% csrf_token %}

    <label for="jmeno">Jméno:</label>
    <input type="text" id="jmeno" name="jmeno" value="{{ pojisteny.jmeno }}"><br>

    <label for="prijmeni">Příjmení:</label>
    <input type="text" id="prijmeni" name="prijmeni" value="{{ pojisteny.prijmeni }}"><br>

    <label for="email">Email:</label>
    <input type="email" id="email" name="email" value="{{ pojisteny.email }}"><br>

    <label for="telefon">Telefon:</label>
    <input type="text" id="telefon" name="telefon" value="{{ pojisteny.telefon }}"><br>

    <label for="ulice">Ulice:</label>
    <input type="text" id="ulice" name="ulice" value="{{ pojisteny.ulice }}"><br>

    <label for="cislo_popisne">Číslo popisné:</label>
    <input type="text" id="cislo_popisne" name="cislo_popisne" value="{{ pojisteny.cislo_popisne }}"><br>

    <label for="mesto">Město:</label>
    <input type="text" id="mesto" name="mesto" value="{{ pojisteny.mesto }}"><br>

    <label for="psc">Psč:</label>
    <input type="text" id="psc" name="psc" value="{{ pojisteny.psc }}"><br>

    <input type="submit" value="Uložit" class="btn btn-primary btn-form"> 


  </form>
  <a href="{% url 'detail_pojisteneho' pk=pojisteny.pk %}" class="btn btn-secondary btn-zrus">Zrušit</a>

  <footer class="pata">
    <div class="row">
        <div class="social">
            <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
            </p>
            <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
            </p>
        </div>
        
  
        <div class="copytext">
            Copywrite &copy; 2023 emixx company.
        </div>
    </div>
  </footer>
</div>
{% endblock %}

mypojisteni/pojisteni/templates/editovat_pojisteni.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">

{% block content %}
<div class="row">
  <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">
  <h1>Editace pojistění</h1>

  <form method="POST" action="">
    {% csrf_token %}

    <label for="nazev">Název:</label>
    <input type="text" id="nazev" name="nazev" value="{{ pojisteni.nazev }}"><br>

    <label for="castka">Částka:</label>
    <input type="number" id="castka" name="castka" value="{{ pojisteni.castka }}"><br>

    <label for="predmet">Předmět:</label>
    <input type="text" id="predmet" name="predmet" value="{{ pojisteni.predmet }}"><br>

    <label for="platnost_od">Platnost od:</label>
    <input type="date" id="platnost_od" name="platnost_od" value="{{ pojisteni.platnost_od|date:'Y-m-d' }}"><br>

    <label for="platnost_do">Platnost do:</label>
    <input type="date" id="platnost_do" name="platnost_do" value="{{ pojisteni.platnost_do|date:'Y-m-d' }}"><br>

    <input type="submit" value="Uložit" class="btn btn-primary btn-form"> 


  </form>
  <a href="{% url 'detail_pojisteneho' pk=pojisteni.pojisteny_objekt.pk %}" class="btn btn-secondary btn-zrus">Zrušit</a>

  <footer class="pata">
    <div class="row">
        <div class="social">
            <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
            </p>
            <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
            </p>
        </div>
        
  
        <div class="copytext">
            Copywrite &copy; 2023 emixx company.
        </div>
    </div>
  </footer>
</div>
{% endblock %}

mypojisteni/pojisteni/templates/novy_pojisteny.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">

{% block content %}
 <div class="row">
    <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">
    <h1>Nový pojištěnec</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-form">Uložit</button>
    </form>
    <a href="{% url 'seznam_pojistenych' %}" class="btn btn-primary btn-zrus">Zrušit</a>

    <footer class="pata">
        <div class="row">
            <div class="social">
                <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
                </p>
                <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
                </p>
            </div>
            
      
            <div class="copytext">
                Copywrite &copy; 2023 emixx company.
            </div>
        </div>
      </footer>
 </div>   
{% endblock %}

mypojisteni/pojisteni/templates/odstranit_pojisteneho.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">

{% block content %}
<div class="row">
  <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">
  <h1>Potvrzení odstranění pojištěného</h1>

<h2 class="upozorneni">Jste si jisti, že chcete odstranit následujícího pojištěného?</h2>

<div class="del-inf">
  <p><strong>Jméno:</strong> {{ pojisteny.jmeno }}</p>
  <p><strong>Příjmení:</strong> {{ pojisteny.prijmeni }}</p>
  <p><strong>Adresa:</strong> {{ pojisteny.ulice }} {{ pojisteny.cislo_popisne }}, {{ pojisteny.mesto }}</p>
  <p><strong>Email:</strong> {{ pojisteny.email }}</p>
  <p><strong>Telefon:</strong> {{ pojisteny.telefon }}</p>
</div>

<form class="form-odstr" method="POST" action="{% url 'odstranit_pojisteneho' pk=pojisteny.pk %}">
  {% csrf_token %}
  <input type="submit" value="Odstranit" class="btn btn-danger">
</form>
<a href="{% url 'detail_pojisteneho' pk=pojisteny.pk %}" class="btn btn-secondary btn-zrus">Zrušit</a>

<footer class="pata">
  <div class="row">
      <div class="social">
          <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
          </p>
          <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
          </p>
      </div>
      

      <div class="copytext">
          Copywrite &copy; 2023 emixx company.
      </div>
  </div>
</footer>
</div>
{% endblock %}

mypojisteni/pojisteni/templates/odstranit_pojisteni.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">


{% block content %}
<div class="row">
  <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">
<h1>Potvrzení odstranění pojištění</h1>

<h2 class="upozorneni">Jste si jisti, že chcete odstranit toto pojištění?</h2>

<div class="del-inf">
  <p><strong>Název pojistění:</strong> {{ pojisteni.nazev }}</p>
  <p><strong>Předmět pojištění:</strong> {{ pojisteni.predmet }}</p>
  <p><strong>Částka:</strong> {{ pojisteni.castka }}</p>
</div>

<form class="form-odstr" method="POST" action="{% url 'odstranit_pojisteni' pk=pojisteni.pk %}">
  {% csrf_token %}
  <input type="submit" value="Odstranit" class="btn btn-danger">
  
</form>
<a href="{% url 'detail_pojisteneho' pk=pojisteny.pk %}" class="btn btn-secondary btn-zrus">Zrušit</a>

<footer class="pata">
  <div class="row">
      <div class="social">
          <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
          </p>
          <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
          </p>
      </div>
      

      <div class="copytext">
          Copywrite &copy; 2023 emixx company.
      </div>
  </div>
</footer>

{% endblock %}

mypojisteni/pojisteni/templates/pridat_pojisteni.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">

{% block content %}
<div class="row">
    <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">
    <h1>Přidat pojištění: {{ pojisteny.jmeno }} {{ pojisteny.prijmeni }}</h1>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="id_pojisteni">Pojištění:</label>
            <input type="text" id="id_pojisteni" name="nazev" value="{{ pojisteni.nazev }}">
        </div>
        <div>
            <label for="id_castka">Částka:</label>
            <input type="text" id="id_castka" name="castka" value="{{ pojisteni.castka }}">
        </div>
        <div>
            <label for="id_predmet">Předmět pojištění:</label>
            <input type="text" id="id_predmet" name="predmet" value="{{ pojisteni.predmet }}">
        </div>
        <div>
            <label for="id_platnost_od">Platnost od:</label>
            <input type="date" id="id_platnost_od" name="platnost_od" value="{{ pojisteni.platnost_od }}">
        </div>
        <div>
            <label for="id_platnost_do">Platnost do:</label>
            <input type="date" id="id_platnost_do" name="platnost_do" value="{{ pojisteni.platnost_do }}">
        </div>
        <button class="btn btn-form" type="submit">Uložit</button>
    </form>

{% if form.errors %}
    <div class="alert alert-danger">
        <strong>Chyba:</strong>
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}
<a href="{% url 'detail_pojisteneho' pk=pojisteny.pk %}" class="btn btn-secondary btn-zrus">Zrušit</a>

<footer class="pata">
    <div class="row">
        <div class="social">
            <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
            </p>
            <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
            </p>
        </div>
        
  
        <div class="copytext">
            Copywrite &copy; 2023 emixx company.
        </div>
    </div>
  </footer>
</div>
{% endblock %}

mypojisteni/pojisteni/templates/seznam_pojistenych.html
{% load static %}

<link rel="stylesheet" href="{% static 'pojisteni/style.css' %}">

{% block content %}
<section class="oba">
  <div class="row">
    <img id="logo" src="{% static 'pojisteni/images/logo6.png' %}" alt="Logo">
    <h1>SEZNAM POJIŠTĚNÝCH</h1>
 
    <div class="centered-button">
        <a href="{% url 'novy_pojisteny' %}" class="btn btn-primary btn-novy">Nový pojištěnec</a>
    </div>
    <form class="form_vyhledat" method="GET" action="{% url 'seznam_pojistenych' %}">
        <input class="vyhledavaci_pole" type="text" name="q" placeholder="Vyhledat pojištěného">
      <p>
        <button class="btn btn_hledat" type="submit">Hledat</button>
      </p>
    </form>
    <ul class="seznam">
    {% for pojisteny in pojisteni %}
        <li><a href="{% url 'detail_pojisteneho' pojisteny.pk %}">{{ pojisteny.jmeno }} {{ pojisteny.prijmeni }}</a></li>
    {% endfor %}
    </ul>
 

    <footer class="pata">
      <div class="row">
          <div class="social">
              <p><a href="https://www.facebook.com/" target="_blank">Facebook</a>
              </p>
              <p><a href="https://www.instagram.com/" target="_blank">Instagram</a>
              </p>
          </div>
          
    
          <div class="copytext">
              Copywrite &copy; 2023 emixx company.
          </div>
      </div>
    </footer>
  </div> 
</section>

{% endblock %}